# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import crash_pb2 as proto_dot_crash__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/crash_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CrashReplicatorStub(object):
    """Service for streaming crash records
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendCrashes = channel.stream_unary(
                '/crashreplication.CrashReplicator/SendCrashes',
                request_serializer=proto_dot_crash__pb2.CrashRecord.SerializeToString,
                response_deserializer=proto_dot_crash__pb2.Ack.FromString,
                _registered_method=True)


class CrashReplicatorServicer(object):
    """Service for streaming crash records
    """

    def SendCrashes(self, request_iterator, context):
        """Client-side streaming RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CrashReplicatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendCrashes': grpc.stream_unary_rpc_method_handler(
                    servicer.SendCrashes,
                    request_deserializer=proto_dot_crash__pb2.CrashRecord.FromString,
                    response_serializer=proto_dot_crash__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'crashreplication.CrashReplicator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('crashreplication.CrashReplicator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CrashReplicator(object):
    """Service for streaming crash records
    """

    @staticmethod
    def SendCrashes(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/crashreplication.CrashReplicator/SendCrashes',
            proto_dot_crash__pb2.CrashRecord.SerializeToString,
            proto_dot_crash__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
