# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import crash_pb2 as proto_dot_crash__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/crash_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CrashReplicatorStub(object):
    """Service for streaming crash records
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendCrashes = channel.stream_unary(
                '/crashreplication.CrashReplicator/SendCrashes',
                request_serializer=proto_dot_crash__pb2.CrashRecord.SerializeToString,
                response_deserializer=proto_dot_crash__pb2.Ack.FromString,
                _registered_method=True)
        self.RequestVote = channel.unary_unary(
                '/crashreplication.CrashReplicator/RequestVote',
                request_serializer=proto_dot_crash__pb2.VoteRequest.SerializeToString,
                response_deserializer=proto_dot_crash__pb2.VoteResponse.FromString,
                _registered_method=True)
        self.AppendEntries = channel.unary_unary(
                '/crashreplication.CrashReplicator/AppendEntries',
                request_serializer=proto_dot_crash__pb2.AppendEntriesRequest.SerializeToString,
                response_deserializer=proto_dot_crash__pb2.AppendEntriesResponse.FromString,
                _registered_method=True)
        self.GetLeader = channel.unary_unary(
                '/crashreplication.CrashReplicator/GetLeader',
                request_serializer=proto_dot_crash__pb2.LeaderRequest.SerializeToString,
                response_deserializer=proto_dot_crash__pb2.LeaderResponse.FromString,
                _registered_method=True)
        self.HeartbeatAck = channel.unary_unary(
                '/crashreplication.CrashReplicator/HeartbeatAck',
                request_serializer=proto_dot_crash__pb2.HeartbeatAckRequest.SerializeToString,
                response_deserializer=proto_dot_crash__pb2.HeartbeatAckResponse.FromString,
                _registered_method=True)
        self.QueryRow = channel.unary_unary(
                '/crashreplication.CrashReplicator/QueryRow',
                request_serializer=proto_dot_crash__pb2.QueryRequest.SerializeToString,
                response_deserializer=proto_dot_crash__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.PropagateResourceScore = channel.unary_unary(
                '/crashreplication.CrashReplicator/PropagateResourceScore',
                request_serializer=proto_dot_crash__pb2.ResourceScoreRequest.SerializeToString,
                response_deserializer=proto_dot_crash__pb2.ResourceScoreResponse.FromString,
                _registered_method=True)
        self.RegisterNode = channel.unary_unary(
                '/crashreplication.CrashReplicator/RegisterNode',
                request_serializer=proto_dot_crash__pb2.RegisterNodeRequest.SerializeToString,
                response_deserializer=proto_dot_crash__pb2.RegisterNodeResponse.FromString,
                _registered_method=True)
        self.UpdateTopology = channel.unary_unary(
                '/crashreplication.CrashReplicator/UpdateTopology',
                request_serializer=proto_dot_crash__pb2.TopologyUpdateRequest.SerializeToString,
                response_deserializer=proto_dot_crash__pb2.TopologyUpdateResponse.FromString,
                _registered_method=True)
        self.UpdateNodeStatus = channel.unary_unary(
                '/crashreplication.CrashReplicator/UpdateNodeStatus',
                request_serializer=proto_dot_crash__pb2.NodeStatusUpdate.SerializeToString,
                response_deserializer=proto_dot_crash__pb2.Ack.FromString,
                _registered_method=True)
        self.GetAllNodes = channel.unary_unary(
                '/crashreplication.CrashReplicator/GetAllNodes',
                request_serializer=proto_dot_crash__pb2.GetAllNodesRequest.SerializeToString,
                response_deserializer=proto_dot_crash__pb2.GetAllNodesResponse.FromString,
                _registered_method=True)


class CrashReplicatorServicer(object):
    """Service for streaming crash records
    """

    def SendCrashes(self, request_iterator, context):
        """Client-side streaming RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestVote(self, request, context):
        """Raft methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendEntries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLeader(self, request, context):
        """Method for leader discovery
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HeartbeatAck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryRow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PropagateResourceScore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterNode(self, request, context):
        """New methods for network resilience
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTopology(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateNodeStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllNodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CrashReplicatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendCrashes': grpc.stream_unary_rpc_method_handler(
                    servicer.SendCrashes,
                    request_deserializer=proto_dot_crash__pb2.CrashRecord.FromString,
                    response_serializer=proto_dot_crash__pb2.Ack.SerializeToString,
            ),
            'RequestVote': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestVote,
                    request_deserializer=proto_dot_crash__pb2.VoteRequest.FromString,
                    response_serializer=proto_dot_crash__pb2.VoteResponse.SerializeToString,
            ),
            'AppendEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendEntries,
                    request_deserializer=proto_dot_crash__pb2.AppendEntriesRequest.FromString,
                    response_serializer=proto_dot_crash__pb2.AppendEntriesResponse.SerializeToString,
            ),
            'GetLeader': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLeader,
                    request_deserializer=proto_dot_crash__pb2.LeaderRequest.FromString,
                    response_serializer=proto_dot_crash__pb2.LeaderResponse.SerializeToString,
            ),
            'HeartbeatAck': grpc.unary_unary_rpc_method_handler(
                    servicer.HeartbeatAck,
                    request_deserializer=proto_dot_crash__pb2.HeartbeatAckRequest.FromString,
                    response_serializer=proto_dot_crash__pb2.HeartbeatAckResponse.SerializeToString,
            ),
            'QueryRow': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryRow,
                    request_deserializer=proto_dot_crash__pb2.QueryRequest.FromString,
                    response_serializer=proto_dot_crash__pb2.QueryResponse.SerializeToString,
            ),
            'PropagateResourceScore': grpc.unary_unary_rpc_method_handler(
                    servicer.PropagateResourceScore,
                    request_deserializer=proto_dot_crash__pb2.ResourceScoreRequest.FromString,
                    response_serializer=proto_dot_crash__pb2.ResourceScoreResponse.SerializeToString,
            ),
            'RegisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterNode,
                    request_deserializer=proto_dot_crash__pb2.RegisterNodeRequest.FromString,
                    response_serializer=proto_dot_crash__pb2.RegisterNodeResponse.SerializeToString,
            ),
            'UpdateTopology': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTopology,
                    request_deserializer=proto_dot_crash__pb2.TopologyUpdateRequest.FromString,
                    response_serializer=proto_dot_crash__pb2.TopologyUpdateResponse.SerializeToString,
            ),
            'UpdateNodeStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateNodeStatus,
                    request_deserializer=proto_dot_crash__pb2.NodeStatusUpdate.FromString,
                    response_serializer=proto_dot_crash__pb2.Ack.SerializeToString,
            ),
            'GetAllNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllNodes,
                    request_deserializer=proto_dot_crash__pb2.GetAllNodesRequest.FromString,
                    response_serializer=proto_dot_crash__pb2.GetAllNodesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'crashreplication.CrashReplicator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('crashreplication.CrashReplicator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CrashReplicator(object):
    """Service for streaming crash records
    """

    @staticmethod
    def SendCrashes(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/crashreplication.CrashReplicator/SendCrashes',
            proto_dot_crash__pb2.CrashRecord.SerializeToString,
            proto_dot_crash__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crashreplication.CrashReplicator/RequestVote',
            proto_dot_crash__pb2.VoteRequest.SerializeToString,
            proto_dot_crash__pb2.VoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crashreplication.CrashReplicator/AppendEntries',
            proto_dot_crash__pb2.AppendEntriesRequest.SerializeToString,
            proto_dot_crash__pb2.AppendEntriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crashreplication.CrashReplicator/GetLeader',
            proto_dot_crash__pb2.LeaderRequest.SerializeToString,
            proto_dot_crash__pb2.LeaderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HeartbeatAck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crashreplication.CrashReplicator/HeartbeatAck',
            proto_dot_crash__pb2.HeartbeatAckRequest.SerializeToString,
            proto_dot_crash__pb2.HeartbeatAckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryRow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crashreplication.CrashReplicator/QueryRow',
            proto_dot_crash__pb2.QueryRequest.SerializeToString,
            proto_dot_crash__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PropagateResourceScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crashreplication.CrashReplicator/PropagateResourceScore',
            proto_dot_crash__pb2.ResourceScoreRequest.SerializeToString,
            proto_dot_crash__pb2.ResourceScoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crashreplication.CrashReplicator/RegisterNode',
            proto_dot_crash__pb2.RegisterNodeRequest.SerializeToString,
            proto_dot_crash__pb2.RegisterNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTopology(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crashreplication.CrashReplicator/UpdateTopology',
            proto_dot_crash__pb2.TopologyUpdateRequest.SerializeToString,
            proto_dot_crash__pb2.TopologyUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateNodeStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crashreplication.CrashReplicator/UpdateNodeStatus',
            proto_dot_crash__pb2.NodeStatusUpdate.SerializeToString,
            proto_dot_crash__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crashreplication.CrashReplicator/GetAllNodes',
            proto_dot_crash__pb2.GetAllNodesRequest.SerializeToString,
            proto_dot_crash__pb2.GetAllNodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
